export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const GET_SEARCH_TEXT = "GET_SEARCH_TEXT";
export const GET_FILTER_STATUS = "GET_FILTER_STATUS";
export const GET_ORDER_LIST = "GET_ORDER_LIST";
export const GET_CATEGORIES_CB = "GET_CATEGORIES_CB"
export const GET_COLORS_CB = "GET_COLORS_CB"
export const GET_CATEGORY_ID = "GET_CATEGORY_ID"